#This prospector captures the docker logs
- input_type: log
  paths:
    - /hostfs/staging-area/water-consumption/*.csv
  exclude_lines: ['^water']
  close_inactive: 24h
  close_renamed: true
  fields:
    indicator: waterconsumption
