#This prospector captures the docker logs
- input_type: log
  paths:
    - /hostfs/staging-area/water-quality/*.csv
  exclude_lines: ['^beach']
  close_inactive: 24h
  close_renamed: true
  fields:
    indicator: waterquality
